[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg", "python3"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install -g pnpm", "pnpm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm run build --if-present"]

[start]
cmd = "pnpm start"
